services:
  pdf-rag:
    build: .
    container_name: pdf-rag-test

    ports:
      - "8000:8000"

    env_file:
      - .env

    environment:
      OLLAMA_HOST: http://host.docker.internal:11434

    volumes:
      - paddle_models:/root/.paddlex

volumes:
  paddle_models: