"""
RAGAS 0.4.3 evaluation using Ollama.

Input:
    ragas_dataset.json

Expected fields:
    question
    answer
    contexts
    ground_truth

Output:
    ragas_results.json

Run:
    python -m rag_ollama.evaluate_ragas
"""

from __future__ import annotations

import argparse
import json
import os
import asyncio
from pathlib import Path
from typing import Any

from datasets import Dataset

from ragas.llms import llm_factory

from ragas.metrics.collections import (
    Faithfulness,
    ContextPrecision,
    ContextRecall,
)

from ragas.embeddings.base import BaseRagasEmbeddings

from sentence_transformers import SentenceTransformer

from openai import AsyncOpenAI

PROJECT_ROOT = Path(__file__).resolve().parents[2]
EVALUATION_DIR = PROJECT_ROOT / "evaluation"

DEFAULT_INPUT = EVALUATION_DIR / "Plantpals_ragas_dataset.json"
DEFAULT_OUTPUT = EVALUATION_DIR / "Plantpals_ragas_results.json"

# ============================================================
# RAGAS Embedding Adapter
# ============================================================

class SentenceTransformerEmbeddings(BaseRagasEmbeddings):
    def __init__(self, model_name: str):
        self.model = SentenceTransformer(model_name)
        print(f"RAGAS embedding model: {model_name}")

    def embed_documents(
        self,
        texts: list[str],
    ) -> list[list[float]]:
        embeddings = self.model.encode(
            texts,
            convert_to_numpy=True,
            normalize_embeddings=True,
        )
        return embeddings.tolist()

    def embed_query(
        self,
        text: str,
    ) -> list[float]:
        embedding = self.model.encode(
            text,
            convert_to_numpy=True,
            normalize_embeddings=True,
        )
        return embedding.tolist()

    async def aembed_documents(
        self,
        texts: list[str],
    ) -> list[list[float]]:
        return self.embed_documents(texts)

    async def aembed_query(
        self,
        text: str,
    ) -> list[float]:
        return self.embed_query(text)

# ============================================================
# Load Dataset
# ============================================================

def load_dataset(
    path: Path
) -> list[dict[str, Any]]:
    """
    Load the dataset generated by evaluate_rag.py.
    """

    if not path.is_file():
        raise FileNotFoundError(
            f"Dataset not found: {path}"
        )

    with path.open(
        "r",
        encoding="utf-8"
    ) as file:

        data = json.load(file)

    if not isinstance(data, list):
        raise ValueError(
            "ragas_dataset.json must contain "
            "a JSON array."
        )

    if not data:
        raise ValueError(
            "ragas_dataset.json is empty."
        )

    return data


# ============================================================
# Prepare Dataset
# ============================================================

def prepare_dataset(
    records: list[dict[str, Any]]
) -> Dataset:
    """
    Convert our JSON format into the dataset format
    expected by RAGAS.
    """

    ragas_records = []

    for index, item in enumerate(
        records,
        start=1
    ):

        question = str(
            item.get(
                "question",
                ""
            )
        ).strip()

        answer = str(
            item.get(
                "answer",
                ""
            )
        ).strip()

        ground_truth = str(
            item.get(
                "ground_truth",
                ""
            )
        ).strip()

        contexts = item.get(
            "contexts",
            item.get(
                "retrieved_contexts",
                []
            )
        )

        if not question:
            raise ValueError(
                f"Record {index} has no question."
            )

        if not isinstance(
            contexts,
            list
        ):
            contexts = [
                str(contexts)
            ]

        contexts = [
            str(context).strip()
            for context in contexts
            if str(context).strip()
        ]

        ragas_records.append(
            {
                "question": question,
                "answer": answer,
                "contexts": contexts,
                "ground_truth": ground_truth,
            }
        )

    return Dataset.from_list(
        ragas_records
    )


# ============================================================
# Create RAGAS Evaluators
# ============================================================

def create_evaluator():
    """
    Create the RAGAS LLM and embedding models.

    LLM:
        qwen2.5:7b
        via Ollama OpenAI-compatible API

    Embeddings:
        all-MiniLM-L6-v2
        via SentenceTransformer
    """

    # --------------------------------------------------------
    # LLM configuration
    # --------------------------------------------------------

    model = os.getenv(
        "RAGAS_OLLAMA_MODEL",
        os.getenv(
            "OLLAMA_MODEL",
            "qwen2.5:7b"
        )
    )

    base_url = os.getenv(
        "OLLAMA_BASE_URL",
        "http://localhost:11434/v1"
    )

    # --------------------------------------------------------
    # Embedding configuration
    # --------------------------------------------------------

    embedding_model = os.getenv(
        "RAGAS_EMBEDDING_MODEL",
        "all-MiniLM-L6-v2"
    )

    print()
    print(
        f"RAGAS evaluator model: "
        f"{model}"
    )

    print(
        f"Ollama URL: "
        f"{base_url}"
    )

    print(
        f"RAGAS embedding model: "
        f"{embedding_model}"
    )

    # --------------------------------------------------------
    # Create Ollama OpenAI-compatible client
    # --------------------------------------------------------

    client = AsyncOpenAI(
        api_key="ollama",
        base_url=base_url,
    )

    # --------------------------------------------------------
    # Create RAGAS-compatible LLM
    # --------------------------------------------------------

    evaluator_llm = llm_factory(
        model,
        provider="openai",
        client=client,
    )

    # --------------------------------------------------------
    # Create RAGAS-compatible embeddings
    # --------------------------------------------------------

    evaluator_embeddings = (
        SentenceTransformerEmbeddings(
            embedding_model
        )
    )

    return (
        evaluator_llm,
        evaluator_embeddings
    )


# ============================================================
# Run Evaluation
# ============================================================

def run_evaluation(
    dataset: Dataset,
    evaluator_llm,
    evaluator_embeddings,
):
    """
    Run RAGAS 0.4.3 collection metrics directly.

    This bypasses ragas.evaluate() because RAGAS 0.4.3
    has a compatibility issue between the new collection
    metrics and the legacy evaluate() type check.
    """

    faithfulness = Faithfulness(
        llm=evaluator_llm
    )

    context_precision = ContextPrecision(
        llm=evaluator_llm
    )

    context_recall = ContextRecall(
        llm=evaluator_llm
    )

    async def evaluate_all():
        results = []

        for index in range(len(dataset)):
            row = dataset[index]

            question = row["question"]
            answer = row["answer"]
            contexts = row["contexts"]
            ground_truth = row["ground_truth"]

            print(
                f"Evaluating {index + 1}/{len(dataset)}..."
            )

            # Default values
            faithfulness_score = None
            context_precision_score = None
            context_recall_score = None

            # ------------------------------------------
            # 1. Faithfulness
            # ------------------------------------------

            try:
                faithfulness_result = await faithfulness.ascore(
                    user_input=question,
                    response=answer,
                    retrieved_contexts=contexts,
                )

                faithfulness_score = float(
                    faithfulness_result.value
                )

            except Exception as e:
                print(
                    f"⚠️ Faithfulness failed "
                    f"for question {index + 1}: {e}"
                )

            # ------------------------------------------
            # 2. Context Precision
            # ------------------------------------------

            try:
                context_precision_result = await context_precision.ascore(
                    user_input=question,
                    reference=ground_truth,
                    retrieved_contexts=contexts,
                )

                context_precision_score = float(
                    context_precision_result.value
                )

            except Exception as e:
                print(
                    f"⚠️ Context precision failed "
                    f"for question {index + 1}: {e}"
                )

            # ------------------------------------------
            # 3. Context Recall
            # ------------------------------------------

            try:
                context_recall_result = await context_recall.ascore(
                    user_input=question,
                    reference=ground_truth,
                    retrieved_contexts=contexts,
                )

                context_recall_score = float(
                    context_recall_result.value
                )

            except Exception as e:
                print(
                    f"⚠️ Context recall failed "
                    f"for question {index + 1}"
                )
                print(f"   Exception type: {type(e).__name__}")
                print(f"   Exception: {repr(e)}")

            # ------------------------------------------
            # Store results
            # ------------------------------------------

            results.append(
                {
                    "faithfulness": faithfulness_score,
                    "context_precision": context_precision_score,
                    "context_recall": context_recall_score,
                }
            )

        return results
    return asyncio.run(evaluate_all())

# ============================================================
# Save Results
# ============================================================

def save_results(
    original_records: list[dict[str, Any]],
    result: list[dict[str, Any]],
    output_path: Path,
):
    """
    Combine the original dataset information
    with RAGAS scores.
    """

    output_records = []

    for index, scores in enumerate(result):

        original = (
            original_records[index]
            if index < len(original_records)
            else {}
        )

        record = {
            "id": original.get("id"),

            "question": original.get(
                "question",
                ""
            ),

            "ground_truth": original.get(
                "ground_truth",
                ""
            ),

            "answer": original.get(
                "answer",
                ""
            ),

            "contexts": original.get(
                "contexts",
                original.get(
                    "retrieved_contexts",
                    []
                )
            ),

            "faithfulness": scores.get(
                "faithfulness"
            ),

            "context_precision": scores.get(
                "context_precision"
            ),

            "context_recall": scores.get(
                "context_recall"
            ),
        }

        output_records.append(record)

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    with output_path.open(
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            output_records,
            file,
            ensure_ascii=False,
            indent=2,
        )

    return output_records


# ============================================================
# Print Summary
# ============================================================

def print_summary(
    results: list[dict[str, Any]]
):

    metrics = [
        "faithfulness",
        "context_precision",
        "context_recall",
    ]

    print()
    print("=" * 70)
    print("RAGAS EVALUATION SUMMARY")
    print("=" * 70)

    for metric in metrics:

        values = [
            item[metric]
            for item in results
            if metric in item
            and isinstance(
                item[metric],
                (int, float)
            )
        ]

        if values:

            average = (
                sum(values)
                / len(values)
            )

            print(
                f"{metric:<22}: "
                f"{average:.4f}"
            )

        else:

            print(
                f"{metric:<22}: "
                f"N/A"
            )

    print(
        f"\nEvaluated records: "
        f"{len(results)}"
    )


# ============================================================
# Main
# ============================================================

def main():

    parser = argparse.ArgumentParser(
        description=(
            "Evaluate a RAG dataset using "
            "RAGAS 0.4.3 and Ollama."
        )
    )

    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT,
        help=(
            "Input RAGAS dataset "
            "(default: evaluation/ragas_dataset2.json)"
        ),
    )

    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=(
            "Output evaluation file "
            "(default: evaluation/ragas_results.json)"
        ),
    )

    args = parser.parse_args()

    # --------------------------------------------------------
    # 1. Load dataset
    # --------------------------------------------------------

    print(
        f"Loading dataset: "
        f"{args.input}"
    )

    records = load_dataset(
        args.input
    )

    print(
        f"Loaded "
        f"{len(records)} records."
    )

    # --------------------------------------------------------
    # 2. Prepare RAGAS Dataset
    # --------------------------------------------------------

    dataset = prepare_dataset(
        records
    )

    print(
        "RAGAS dataset prepared."
    )

    # --------------------------------------------------------
    # 3. Create evaluator
    # --------------------------------------------------------

    (
        evaluator_llm,
        evaluator_embeddings
    ) = create_evaluator()

    # --------------------------------------------------------
    # 4. Run RAGAS
    # --------------------------------------------------------

    result = run_evaluation(
        dataset,
        evaluator_llm,
        evaluator_embeddings
    )

    # --------------------------------------------------------
    # 5. Save results
    # --------------------------------------------------------

    results = save_results(
        records,
        result,
        args.output
    )

    # --------------------------------------------------------
    # 6. Print summary
    # --------------------------------------------------------

    print_summary(
        results
    )

    print()
    print(
        f"Results saved to: "
        f"{args.output}"
    )


# ============================================================
# Entry Point
# ============================================================

if __name__ == "__main__":
    main()
